-- Standard function

-- DUAL : 가상 테이블 -> 결과 확인용 임시 테이블
SELECT 1 FROM DUAL;
SELECT 'A' FROM DUAL;
SELECT '가' FROM DUAL;
SELECT 32 * 24 FROM DUAL;

-- 문자함수
-- CHR(N) : ASCII 값을 문자로 변환
SELECT CHR(65) FROM DUAL;
SELECT CHR(97) FROM DUAL;

-- 내 점수는 A 입니다
SELECT '내 점수는 ' || CHR(65) || ' 입니다' FROM DUAL;
-- "내 점수는 " + CHR(65) + " 입니다"

-- LPAD(RPAD) : 나머지를 빈칸(특정문자)으로 채운다
SELECT LPAD('BBB', 10) FROM DUAL;
SELECT RPAD('BBB', 10) FROM DUAL;
SELECT LPAD('BBB', 10, '-') FROM DUAL;
SELECT LPAD('BBB', 10, '7') FROM DUAL;

-- INSTR == indexOf('a') java -> 0~ db -> 1~
SELECT INSTR('123A456B678C', 'A') FROM DUAL;
SELECT INSTR('123A456B678CB', 'B', 9) FROM DUAL;
SELECT INSTR('123A456B678CB', 'B', 4, 1) FROM DUAL; -- 1번째
SELECT INSTR('123A456B678CB', 'B', 4, 2) FROM DUAL; -- 2번째

-- REPLACE : 문자열 치환
SELECT REPLACE('AAAAABCD', 'A') FROM DUAL;
SELECT REPLACE('AAAAABCD', 'A', 'a') FROM DUAL;
SELECT REPLACE('AAAAABCD', 'AA', 'a') FROM DUAL;

-- TRANSLATE : 문자 치환
SELECT TRANSLATE('AAAAABCD', 'A', 'a') FROM DUAL;
SELECT TRANSLATE('AAAAABCD', 'AB', 'a') FROM DUAL;

-- 숫자 함수
-- 올림
SELECT CEIL(13.1) FROM DUAL;

-- 내림
SELECT FLOOR(13.9) FROM DUAL;

-- 나눈 나머지
SELECT MOD(3, 2) FROM DUAL;

-- 승수
SELECT POWER(3, 2) FROM DUAL;

-- 반올림
SELECT ROUND(13.5) FROM DUAL;

-- 부호 +:1 0:0 -:-1
SELECT SIGN(13.4) FROM DUAL;
SELECT SIGN(0) FROM DUAL;
SELECT SIGN(-3.4) FROM DUAL;

-- 버림
SELECT TRUNC(12.3456) FROM DUAL;
SELECT TRUNC(12.3456, 2) FROM DUAL;
SELECT TRUNC(12.3456, -1) FROM DUAL;

-- CHR <->
SELECT ASCII('A') FROM DUAL;

-- 변환 함수 
-- TO_CHAR  DATE -> STRING
SELECT TO_CHAR(SYSDATE)
FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'YYYY-MM-DD-HH-MI-SS')
FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'YYYY-MM-DD HH:MI:SS')
FROM DUAL;

SELECT TO_CHAR(100000000000, '$999,999,999,999')
FROM DUAL;

-- TO_DATE  STRING -> DATE
SELECT TO_DATE('20191225')
FROM DUAL;

SELECT TO_DATE('20191225', 'YYYYMMDD')
FROM DUAL;

SELECT TO_DATE('12252019', 'MMDDYYYY')
FROM DUAL;

-- TO_NUMBER    -> parseInt
SELECT TO_NUMBER('112') + 24
FROM DUAL;

-- LAST_DAY
SELECT LAST_DAY('19/11/01')
FROM DUAL;

SELECT LAST_DAY(TO_DATE('19-11-01', 'YYYY-MM-DD'))
FROM DUAL;

-- SUBSTR   substring(1, 3)  "ABCDE" -> BC
SELECT SUBSTR('ABCDE', 3)   -- 3번째 문자부터 끝까지
FROM DUAL;

SELECT SUBSTR('ABCDE', 3, 2)   -- 3번째 문자부터 2개의 문자까지
FROM DUAL;

-- LENGTHB -> 문자의 길이 BYTE형식
-- LENGTH -> 문자길이
SELECT LENGTH('ABCDE') FROM DUAL;
